---
- name: Update APT
  apt: update_cache=yes
#- name: Install aptitude package #due to bug https://github.com/ansible/ansible-modules-core/issues/3523
#  action: apt name="aptitude"
#- name: Upgrade APT
#  apt: upgrade=yes
- name: Install usual packages
  action: apt name="{{ item }}" state=latest update_cache=true
  with_items:
    - dstat
    - joe
    - git
    - python-software-properties
 
